apiVersion: apps/v1
kind: Deployment
metadata:
  name: deevenapp01
spec:
  selector:
    matchLabels:
      app: deeven01-pod
  template:
    metadata:
      labels:
        app: deeven01-pod
    spec:
      containers:
      - name: deeven01-container
        image: barclaysacr02.azurecr.io/deeven01:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
